import oracledb
import os
from dotenv import load_dotenv

# 1. Load the vault
load_dotenv()

# 2. Map the keys from .env to Python variables
DB_USER = "ADMIN"
DB_PASS = os.getenv("DB_PASSWORD") 
DB_DSN = "mcpvectordb_low" 
WALLET_PWD = os.getenv("WALLET_PASSWORD") # This pulls the password from .env

# 3. Path to your wallet
WALLET_PATH = "/workspaces/3_cloud_MCP_Project/network/admin"

def initialize_with_wallet():
    try:
        # Connecting using the variables we pulled from the .env
        conn = oracledb.connect(
            user=DB_USER,
            password=DB_PASS,
            dsn=DB_DSN,
            config_dir=WALLET_PATH,
            wallet_location=WALLET_PATH,
            wallet_password=WALLET_PWD # ✅ Now using the variable, not the raw text
        )
        print("🔒 Secure Wallet Connection Established!")
        
        cursor = conn.cursor()
        cursor.execute("SELECT 'Hello from Oracle AI DB' FROM DUAL")
        print(f"Database response: {cursor.fetchone()[0]}")
        
        # Create the table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS resume_vectors (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content CLOB,
                metadata JSON,
                embedding VECTOR(1536, FLOAT32)
            )
        """)
        print("🚀 Vector Table 'resume_vectors' is ready.")
        
        conn.commit()
        cursor.close()
        conn.close()
        
    except Exception as e:
        print(f"❌ Wallet Connection Failed: {e}")

if __name__ == "__main__":
    initialize_with_wallet()