import os
import json
import boto3
from dotenv import load_dotenv
from src.mcp_servers.retrieval_server import search_resume

load_dotenv()

def call_bedrock_llm(prompt):
    """Calls AWS Bedrock Converse API with Amazon Nova Lite to generate responses."""
    client = boto3.client("bedrock-runtime", region_name="us-east-1")
    
    response = client.converse(
        modelId="amazon.nova-lite-v1:0",
        messages=[
            {
                "role": "user",
                "content": [{"text": prompt}]
            }
        ],
        inferenceConfig={
            "maxTokens": 1024,  # Expanded to handle full document output
            "temperature": 0.2, # Lowered temperature for strict template adherence
            "topP": 0.9
        }
    )
    return response["output"]["message"]["content"][0]["text"]

def load_cover_letter_template():
    """Loads the base cover letter text file from the data directory."""
    template_path = "data/cover_letter_template.txt"
    if os.path.exists(template_path):
        with open(template_path, "r", encoding="utf-8") as f:
            return f.read()
    else:
        # Balanced fallback baseline if the file isn't created yet
        return (
            "Dear Hiring Team,\n\nI am highly interested in joining your team. "
            "I have a strong background in Python and SQL database management pipelines, "
            "and I look forward to contributing to your active operations.\n\nSincerely,\nColin Keith"
        )

def tailor_application_profile(job_description):
    print("🎯 Step 1: Analyzing the job description requirements...")
    search_query = "Python SQL data pipelines cloud predictive models"
    
    print("📡 Step 2: Fetching matching semantic context from Oracle 23ai...")
    retrieved_context = search_resume(search_query)
    
    print("📖 Step 3: Loading cover letter baseline template...")
    base_cover_letter = load_cover_letter_template()
    
    print("🧠 Step 4: Execution engineering via Amazon Nova Lite...")
    orchestration_prompt = f"""
    You are an expert career placement agent. Your task is to take the candidate's ORIGINAL COVER LETTER TEMPLATE and SLIGHTLY modify it to match a specific target job.

    TARGET JOB DESCRIPTION:
    {job_description}
    
    CANDIDATE'S SEMANTICALLY MATCHED DATA FROM ORACLE:
    {retrieved_context}
    
    ORIGINAL COVER LETTER TEMPLATE:
    \"\"\"
    {base_cover_letter}
    \"\"\"
    
    CRITICAL INSTRUCTIONS:
    1. Maintain the overall structure, paragraphs, introduction, and conclusion of the ORIGINAL COVER LETTER TEMPLATE.
    2. Do NOT rewrite the document completely. Keep the edits highly targeted and minimal.
    3. Update the greeting, company name, and job title fields to match the Target Job Description naturally.
    4. Subtly adjust 1 or 2 sentences inside the core body paragraph to seamlessly integrate the specific metrics or skills found in the CANDIDATE'S SEMANTICALLY MATCHED DATA (such as explicit database records processed or automated pipeline development) to align directly with what the job asks for.
    5. Output the final tailored cover letter in full. Do not include notes, labels, or introductory text outside of the letter itself.
    """
    
    tailored_document = call_bedrock_llm(orchestration_prompt)
    return tailored_document

if __name__ == "__main__":
    SAMPLE_JOB = """
    We are seeking an Analyst who can manage massive datasets and construct automated pipelines. 
    The ideal candidate has exceptional skills in Python and SQL database environments, with an interest in deploying data models.
    """
    
    print("🚀 Launching Template-Driven Tailoring Agent Loop...\n")
    result = tailor_application_profile(SAMPLE_JOB)
    
    print("\n📝 TAILORED COVER LETTER GENERATED BY AGENT:")
    print("=" * 60)
    print(result.strip())
    print("=" * 60)